"""blocks cards tables

Revision ID: 2bf2ef7ffead
Revises: 8c7750155fb0
Create Date: 2025-11-07 14:05:33.357098

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2bf2ef7ffead"
down_revision: Union[str, Sequence[str], None] = "8c7750155fb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocks",
        sa.Column("title", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=30), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("draft", "active", "archived", name="block_status"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("roadmap_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["roadmap_id"],
            ["roadmaps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cards",
        sa.Column("term", sa.String(length=40), nullable=False),
        sa.Column("definition", sa.String(length=40), nullable=False),
        sa.Column("example", sa.String(length=40), nullable=False),
        sa.Column("comment", sa.String(length=40), nullable=False),
        sa.Column(
            "status", sa.Enum("unknown", "known", "review", name="card_status"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("block_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["blocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cards")
    op.drop_table("blocks")
    # ### end Alembic commands ###
