"""upd. user table

Revision ID: 3643046ad461
Revises: 353de4cbf98b
Create Date: 2025-11-10 16:17:03.342636

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3643046ad461"
down_revision: Union[str, Sequence[str], None] = "353de4cbf98b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_superuser", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), nullable=False))
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=320),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=1024),
        existing_nullable=False,
    )
    # op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    # op.create_unique_constraint(
    #     op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    # )
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=320),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.drop_column("users", "is_verified")
    op.drop_column("users", "is_superuser")
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
