"""Nullable fields

Revision ID: f9d2aa531f44
Revises: 5fcbe25ded91
Create Date: 2025-11-24 15:27:28.022803

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f9d2aa531f44"
down_revision: Union[str, Sequence[str], None] = "5fcbe25ded91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    op.alter_column(
        "blocks",
        "description",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=100),
        nullable=True,
    )
    op.alter_column(
        "cards",
        "term",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "cards",
        "definition",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "cards",
        "example",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=100),
        nullable=True,
    )
    op.alter_column(
        "cards",
        "comment",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=100),
        nullable=True,
    )
    op.alter_column(
        "roadmaps", "description", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "roadmaps", "description", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "cards",
        "comment",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=40),
        nullable=False,
    )
    op.alter_column(
        "cards",
        "example",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=40),
        nullable=False,
    )
    op.alter_column(
        "cards",
        "definition",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=40),
        existing_nullable=False,
    )
    op.alter_column(
        "cards",
        "term",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=40),
        existing_nullable=False,
    )
    op.alter_column(
        "blocks",
        "description",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=30),
        nullable=False,
    )
    op.create_table(
        "sessions",
        sa.Column(
            "mode",
            postgresql.ENUM("review", "exam", name="session_mode"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("active", "completed", "abandoned", name="session_status"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "card_queue",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "current_card_index", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("correct_answers", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "incorrect_answers", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("review_answers", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("roadmap_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("block_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["block_id"], ["blocks.id"], name=op.f("sessions_block_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["roadmap_id"], ["roadmaps.id"], name=op.f("sessions_roadmap_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("sessions_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sessions_pkey")),
    )
    # ### end Alembic commands ###
