"""add on delete cascade

Revision ID: d15bbc5f3fc3
Revises: dbfa550e26b9
Create Date: 2026-01-09 21:18:53.068136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d15bbc5f3fc3"
down_revision: Union[str, Sequence[str], None] = "dbfa550e26b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # op.drop_constraint(op.f("fk_access_tokens_user_id_users"), "access_tokens", type_="foreignkey")  # ←
    # op.create_foreign_key(
    #     op.f("fk_access_tokens_user_id_users"),
    #     "access_tokens",
    #     "users",
    #     ["user_id"],
    #     ["id"],
    #     ondelete="CASCADE",
    # )
    # op.drop_constraint(op.f("blocks_roadmap_id_fkey"), "blocks", type_="foreignkey")  # ← ТЕКУЩАЯ ОШИБКА
    # op.create_foreign_key(
    #     op.f("fk_blocks_roadmap_id_roadmaps"),
    #     "blocks",
    #     "roadmaps",
    #     ["roadmap_id"],
    #     ["id"],
    #     ondelete="CASCADE",
    # )
    # op.drop_constraint(op.f("cards_block_id_fkey"), "cards", type_="foreignkey")  # ←
    # op.create_foreign_key(
    #     op.f("fk_cards_block_id_blocks"),
    #     "cards",
    #     "blocks",
    #     ["block_id"],
    #     ["id"],
    #     ondelete="CASCADE",
    # )
    # op.drop_constraint(op.f("roadmaps_user_id_fkey"), "roadmaps", type_="foreignkey")  # ←
    # op.create_foreign_key(
    #     op.f("fk_roadmaps_user_id_users"),
    #     "roadmaps",
    #     "users",
    #     ["user_id"],
    #     ["id"],
    #     ondelete="CASCADE",
    # )
    # op.drop_constraint(op.f("fk_sessions_roadmap_id_roadmaps"), "sessions", type_="foreignkey")  # ←
    # op.drop_constraint(op.f("fk_sessions_user_id_users"), "sessions", type_="foreignkey")  # ←
    # op.create_foreign_key(
    #     op.f("fk_sessions_roadmap_id_roadmaps"),
    #     "sessions",
    #     "roadmaps",
    #     ["roadmap_id"],
    #     ["id"],
    #     ondelete="CASCADE",
    # )
    # op.create_foreign_key(
    #     op.f("fk_sessions_user_id_users"),
    #     "sessions",
    #     "users",
    #     ["user_id"],
    #     ["id"],
    #     ondelete="CASCADE",
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(
    #     op.f("fk_sessions_user_id_users"), "sessions", type_="foreignkey"
    # )
    # op.drop_constraint(
    #     op.f("fk_sessions_roadmap_id_roadmaps"), "sessions", type_="foreignkey"
    # )
    # op.create_foreign_key(
    #     op.f("fk_sessions_user_id_users"), "sessions", "users", ["user_id"], ["id"]
    # )
    # op.create_foreign_key(
    #     op.f("fk_sessions_roadmap_id_roadmaps"),
    #     "sessions",
    #     "roadmaps",
    #     ["roadmap_id"],
    #     ["id"],
    # )
    # op.drop_constraint(
    #     op.f("fk_roadmaps_user_id_users"), "roadmaps", type_="foreignkey"
    # )
    # op.create_foreign_key(
    #     op.f("roadmaps_user_id_fkey"), "roadmaps", "users", ["user_id"], ["id"]
    # )
    # op.drop_constraint(op.f("fk_cards_block_id_blocks"), "cards", type_="foreignkey")
    # op.create_foreign_key(
    #     op.f("cards_block_id_fkey"), "cards", "blocks", ["block_id"], ["id"]
    # )
    # op.drop_constraint(
    #     op.f("fk_blocks_roadmap_id_roadmaps"), "blocks", type_="foreignkey"
    # )
    # op.create_foreign_key(
    #     op.f("blocks_roadmap_id_fkey"), "blocks", "roadmaps", ["roadmap_id"], ["id"]
    # )
    # op.drop_constraint(
    #     op.f("fk_access_tokens_user_id_users"), "access_tokens", type_="foreignkey"
    # )
    # op.create_foreign_key(
    #     op.f("fk_access_tokens_user_id_users"),
    #     "access_tokens",
    #     "users",
    #     ["user_id"],
    #     ["id"],
    # )
    # ### end Alembic commands ###
