"""add timezone on expires_at at access_tokens

Revision ID: 3a8f51703c32
Revises: 32f52270794e
Create Date: 2026-01-30 17:29:03.639782

"""

from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a8f51703c32"
down_revision: Union[str, Sequence[str], None] = "32f52270794e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "access_tokens",
        sa.Column(
            "expires_at",
            fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_access_tokens_expires_at"),
        "access_tokens",
        ["expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_access_tokens_expires_at"), table_name="access_tokens")
    op.drop_column("access_tokens", "expires_at")
    # ### end Alembic commands ###
