"""add user_id to Block, Card

Revision ID: 32f52270794e
Revises: d15bbc5f3fc3
Create Date: 2026-01-24 12:36:00.202884

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32f52270794e"
down_revision: Union[str, Sequence[str], None] = "d15bbc5f3fc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_access_tokens_user_id_users"), "access_tokens", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_access_tokens_user_id_users"),
        "access_tokens",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("blocks", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.drop_constraint(op.f("fk_blocks_roadmap_id_roadmaps"), "blocks", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_blocks_roadmap_id_roadmaps"),
        "blocks",
        "roadmaps",
        ["roadmap_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_blocks_user_id_users"), "blocks", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("cards", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.drop_constraint(op.f("fk_cards_block_id_blocks"), "cards", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_cards_block_id_blocks"),
        "cards",
        "blocks",
        ["block_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_cards_user_id_users"), "cards", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("fk_roadmaps_user_id_users"), "roadmaps", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_roadmaps_user_id_users"),
        "roadmaps",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("fk_sessions_roadmap_id_roadmaps"), "sessions", type_="foreignkey")
    op.drop_constraint(op.f("fk_sessions_user_id_users"), "sessions", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_sessions_roadmap_id_roadmaps"),
        "sessions",
        "roadmaps",
        ["roadmap_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_sessions_user_id_users"),
        "sessions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_users_email"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.drop_constraint(op.f("fk_sessions_user_id_users"), "sessions", type_="foreignkey")
    op.drop_constraint(op.f("fk_sessions_roadmap_id_roadmaps"), "sessions", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_sessions_user_id_users"), "sessions", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_sessions_roadmap_id_roadmaps"), "sessions", "roadmaps", ["roadmap_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_roadmaps_user_id_users"), "roadmaps", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_roadmaps_user_id_users"), "roadmaps", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_cards_user_id_users"), "cards", type_="foreignkey")
    op.drop_constraint(op.f("fk_cards_block_id_blocks"), "cards", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_cards_block_id_blocks"), "cards", "blocks", ["block_id"], ["id"]
    )
    op.drop_column("cards", "user_id")
    op.drop_constraint(op.f("fk_blocks_user_id_users"), "blocks", type_="foreignkey")
    op.drop_constraint(op.f("fk_blocks_roadmap_id_roadmaps"), "blocks", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_blocks_roadmap_id_roadmaps"), "blocks", "roadmaps", ["roadmap_id"], ["id"]
    )
    op.drop_column("blocks", "user_id")
    op.drop_constraint(op.f("fk_access_tokens_user_id_users"), "access_tokens", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_access_tokens_user_id_users"), "access_tokens", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
